<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="g1">
  <!--
    Unitree G1 Humanoid Robot URDF
    29 DOF Configuration:
    - 6 joints per leg (12 total for locomotion)
    - 3 joints in waist/torso
    - 7 joints per arm (14 total for manipulation)
  -->

  <!-- Properties -->
  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Materials -->
  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="light_grey">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.0 0.4 0.8 1.0"/>
  </material>

  <!-- Base Link (Pelvis) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.12 0.10"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.12 0.10"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.02"/>
    </inertial>
  </link>

  <!-- ==================== WAIST/TORSO (3 DOF) ==================== -->

  <!-- Waist Yaw -->
  <joint name="waist_yaw_joint" type="revolute">
    <parent link="base_link"/>
    <child link="waist_yaw_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.75" upper="0.75" effort="100" velocity="3.0"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>

  <link name="waist_yaw_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.05"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.003"/>
    </inertial>
  </link>

  <!-- Waist Roll -->
  <joint name="waist_roll_joint" type="revolute">
    <parent link="waist_yaw_link"/>
    <child link="waist_roll_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.35" upper="0.35" effort="100" velocity="3.0"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>

  <link name="waist_roll_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.055" length="0.05"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.055" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="1.2"/>
      <inertia ixx="0.004" ixy="0" ixz="0" iyy="0.004" iyz="0" izz="0.002"/>
    </inertial>
  </link>

  <!-- Waist Pitch (connects to torso) -->
  <joint name="waist_pitch_joint" type="revolute">
    <parent link="waist_roll_link"/>
    <child link="torso_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.35" upper="0.35" effort="100" velocity="3.0"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>

  <!-- Torso Link -->
  <link name="torso_link">
    <visual>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <geometry>
        <box size="0.20 0.25 0.30"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <geometry>
        <box size="0.20 0.25 0.30"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <mass value="8.0"/>
      <inertia ixx="0.15" ixy="0" ixz="0" iyy="0.12" iyz="0" izz="0.08"/>
    </inertial>
  </link>

  <!-- Head (fixed) -->
  <joint name="head_joint" type="fixed">
    <parent link="torso_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
  </joint>

  <link name="head_link">
    <visual>
      <origin xyz="0 0 0.08" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.12 0.16"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.08" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.12 0.16"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.08" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.003"/>
    </inertial>
  </link>

  <!-- ==================== ARM MACRO (7 DOF each) ==================== -->
  <xacro:macro name="arm" params="side parent y_offset">

    <!-- Shoulder Pitch -->
    <joint name="${side}_shoulder_pitch_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${side}_shoulder_pitch_link"/>
      <origin xyz="0 ${y_offset * 0.15} 0.25" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-2.87" upper="2.87" effort="50" velocity="5.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <link name="${side}_shoulder_pitch_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Shoulder Roll -->
    <joint name="${side}_shoulder_roll_joint" type="revolute">
      <parent link="${side}_shoulder_pitch_link"/>
      <child link="${side}_shoulder_roll_link"/>
      <origin xyz="0 ${y_offset * 0.02} 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-1.5 if y_offset > 0 else -0.3}" upper="${0.3 if y_offset > 0 else 1.5}" effort="50" velocity="5.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <link name="${side}_shoulder_roll_link">
      <visual>
        <origin xyz="0 ${y_offset * 0.05} 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.03" length="0.08"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 ${y_offset * 0.05} 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.03" length="0.08"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 ${y_offset * 0.05} 0" rpy="0 0 0"/>
        <mass value="0.6"/>
        <inertia ixx="0.0008" ixy="0" ixz="0" iyy="0.0008" iyz="0" izz="0.0005"/>
      </inertial>
    </link>

    <!-- Shoulder Yaw -->
    <joint name="${side}_shoulder_yaw_joint" type="revolute">
      <parent link="${side}_shoulder_roll_link"/>
      <child link="${side}_upper_arm_link"/>
      <origin xyz="0 ${y_offset * 0.08} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="50" velocity="5.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <link name="${side}_upper_arm_link">
      <visual>
        <origin xyz="0 ${y_offset * 0.08} -0.08" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.16"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 ${y_offset * 0.08} -0.08" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.16"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 ${y_offset * 0.08} -0.08" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Elbow -->
    <joint name="${side}_elbow_joint" type="revolute">
      <parent link="${side}_upper_arm_link"/>
      <child link="${side}_lower_arm_link"/>
      <origin xyz="0 ${y_offset * 0.08} -0.16" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2.35 if y_offset > 0 else 0}" upper="${0 if y_offset > 0 else 2.35}" effort="50" velocity="5.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <link name="${side}_lower_arm_link">
      <visual>
        <origin xyz="0 0 -0.08" rpy="0 0 0"/>
        <geometry>
          <box size="0.04 0.04 0.16"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 -0.08" rpy="0 0 0"/>
        <geometry>
          <box size="0.04 0.04 0.16"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -0.08" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.0008"/>
      </inertial>
    </link>

    <!-- Wrist Yaw -->
    <joint name="${side}_wrist_yaw_joint" type="revolute">
      <parent link="${side}_lower_arm_link"/>
      <child link="${side}_wrist_yaw_link"/>
      <origin xyz="0 0 -0.16" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="20" velocity="5.0"/>
      <dynamics damping="0.3" friction="0.05"/>
    </joint>

    <link name="${side}_wrist_yaw_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="0.03"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.2"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- Wrist Roll -->
    <joint name="${side}_wrist_roll_joint" type="revolute">
      <parent link="${side}_wrist_yaw_link"/>
      <child link="${side}_wrist_roll_link"/>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-1.57" upper="1.57" effort="20" velocity="5.0"/>
      <dynamics damping="0.3" friction="0.05"/>
    </joint>

    <link name="${side}_wrist_roll_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="0.03"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.15"/>
        <inertia ixx="0.00008" ixy="0" ixz="0" iyy="0.00008" iyz="0" izz="0.00005"/>
      </inertial>
    </link>

    <!-- Wrist Pitch (connects to hand) -->
    <joint name="${side}_wrist_pitch_joint" type="revolute">
      <parent link="${side}_wrist_roll_link"/>
      <child link="${side}_hand_link"/>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.0" upper="1.0" effort="20" velocity="5.0"/>
      <dynamics damping="0.3" friction="0.05"/>
    </joint>

    <link name="${side}_hand_link">
      <visual>
        <origin xyz="0 0 -0.04" rpy="0 0 0"/>
        <geometry>
          <box size="0.06 0.08 0.08"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 -0.04" rpy="0 0 0"/>
        <geometry>
          <box size="0.06 0.08 0.08"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -0.04" rpy="0 0 0"/>
        <mass value="0.4"/>
        <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0003"/>
      </inertial>
    </link>

  </xacro:macro>

  <!-- ==================== LEG MACRO (6 DOF each) ==================== -->
  <xacro:macro name="leg" params="side parent y_offset">

    <!-- Hip Yaw -->
    <joint name="${side}_hip_yaw_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${side}_hip_yaw_link"/>
      <origin xyz="0 ${y_offset * 0.05} -0.05" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.43" upper="0.43" effort="150" velocity="3.0"/>
      <dynamics damping="2.0" friction="0.2"/>
    </joint>

    <link name="${side}_hip_yaw_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.04"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.04"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Hip Roll -->
    <joint name="${side}_hip_roll_joint" type="revolute">
      <parent link="${side}_hip_yaw_link"/>
      <child link="${side}_hip_roll_link"/>
      <origin xyz="0 ${y_offset * 0.02} -0.02" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-0.43 if y_offset > 0 else -0.43}" upper="${0.43 if y_offset > 0 else 0.43}" effort="150" velocity="3.0"/>
      <dynamics damping="2.0" friction="0.2"/>
    </joint>

    <link name="${side}_hip_roll_link">
      <visual>
        <origin xyz="0 ${y_offset * 0.03} 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.035" length="0.06"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 ${y_offset * 0.03} 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="0.035" length="0.06"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 ${y_offset * 0.03} 0" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.0015" ixy="0" ixz="0" iyy="0.0015" iyz="0" izz="0.0008"/>
      </inertial>
    </link>

    <!-- Hip Pitch -->
    <joint name="${side}_hip_pitch_joint" type="revolute">
      <parent link="${side}_hip_roll_link"/>
      <child link="${side}_thigh_link"/>
      <origin xyz="0 ${y_offset * 0.05} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="0.52" effort="200" velocity="3.0"/>
      <dynamics damping="2.0" friction="0.2"/>
    </joint>

    <link name="${side}_thigh_link">
      <visual>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.07 0.07 0.30"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.07 0.07 0.30"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <mass value="3.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.005"/>
      </inertial>
    </link>

    <!-- Knee -->
    <joint name="${side}_knee_joint" type="revolute">
      <parent link="${side}_thigh_link"/>
      <child link="${side}_calf_link"/>
      <origin xyz="0 0 -0.30" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0.0" upper="2.53" effort="200" velocity="3.0"/>
      <dynamics damping="2.0" friction="0.2"/>
    </joint>

    <link name="${side}_calf_link">
      <visual>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.30"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.30"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -0.15" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.003"/>
      </inertial>
    </link>

    <!-- Ankle Pitch -->
    <joint name="${side}_ankle_pitch_joint" type="revolute">
      <parent link="${side}_calf_link"/>
      <child link="${side}_ankle_link"/>
      <origin xyz="0 0 -0.30" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.87" upper="0.52" effort="100" velocity="3.0"/>
      <dynamics damping="1.5" friction="0.15"/>
    </joint>

    <link name="${side}_ankle_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.03"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.0003" ixy="0" ixz="0" iyy="0.0003" iyz="0" izz="0.0002"/>
      </inertial>
    </link>

    <!-- Ankle Roll -->
    <joint name="${side}_ankle_roll_joint" type="revolute">
      <parent link="${side}_ankle_link"/>
      <child link="${side}_foot_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-0.26" upper="0.26" effort="100" velocity="3.0"/>
      <dynamics damping="1.5" friction="0.15"/>
    </joint>

    <link name="${side}_foot_link">
      <visual>
        <origin xyz="0.03 0 -0.02" rpy="0 0 0"/>
        <geometry>
          <box size="0.18 0.08 0.04"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.03 0 -0.02" rpy="0 0 0"/>
        <geometry>
          <box size="0.18 0.08 0.04"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.03 0 -0.02" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.003"/>
      </inertial>
    </link>

  </xacro:macro>

  <!-- ==================== INSTANTIATE LIMBS ==================== -->

  <!-- Left Arm (y_offset = 1) -->
  <xacro:arm side="left" parent="torso_link" y_offset="1"/>

  <!-- Right Arm (y_offset = -1) -->
  <xacro:arm side="right" parent="torso_link" y_offset="-1"/>

  <!-- Left Leg (y_offset = 1) -->
  <xacro:leg side="left" parent="base_link" y_offset="1"/>

  <!-- Right Leg (y_offset = -1) -->
  <xacro:leg side="right" parent="base_link" y_offset="-1"/>

</robot>
